App/models.py
import string
from random import choices
from sqlalchemy.sql import func
from .extensions import db
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length



class Urls(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(1000))
    shortened_url = db.Column(db.String(5), unique=True)

    def __repr__(self):
        return f"Urls('{self.url}', '{self.shortened_url}')"

def find_url(url):
    link = Urls.query.filter_by(url=url).first()
    print(link)
    return link


def find_short(shortened_url):
    link = Urls.query.filter_by(shortened_url=shortened_url).first()
    print(link)
    return link


class Form(FlaskForm):
    url = StringField('URL', validators=[DataRequired(), Length(min=5, max=250)])
    submit = SubmitField('Submit')


    # def __init__(self, **kwargs):
    #     super().__init__(**kwargs)
    #     self.shortened_url = self.shortener()

    # def shortener(self):
    #     char = string.ascii_letters + string.digits
    #     shortened_url = ''.join(choices(char, k=5))

    #     link = self.query.filter_by(shortened_url=shortened_url).first()

    #     if link:
    #         return self.shortener()

    #     return shortened_url

App/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from .views import views
from .extensions import db


DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'JJJ'

    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    create_database(app)


    app.register_blueprint(views)
    return app

def create_database(app):
    if not path.exists('App/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

App/views.py
from flask import Blueprint, redirect, render_template, request, flash, jsonify
from .extensions import db
import json
from werkzeug import exceptions
import shortuuid
from .models import Urls, find_url, find_short, Form




views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
def home():
    form = Form()
    print(form)
    if request.method == 'POST':
        if find_url(form.url.data):
            link = find_url(form.url.data).url
            short = find_url(form.url.data).shortened_url
            return render_template('new_link.html', url=link, shortened_url=short)
        else:
            short = shortuuid.uuid()[:5]
            url = Urls(url=form.url.data, shortned_url=short)
            db.session.add(url)
            db.session.commit()
            return render_template('home.html', url=url.url, shortened_url=short)
    else:
        return render_template('home.html', title ='home')
    

@views.route('/new_link', methods = ['POST'])
def new_link():
    url = request.form.get('url')
    link = Urls(url=url)
    db.session.add(link)
    db.session.commit()

    return render_template('new_link.html', new_link = link.shortened_url, url=link.url, title='new_link')

@views.route('/<shortened_url>')
def to_new_link(shortened_url):
    link = Urls.query.filter_by(shortened_url=shortened_url).first_or_404()
    return redirect(link.url)


@views.errorhandler(exceptions.NotFound)
def handle_404(err):
    return render_template('errors/404.html'), 404

@views.errorhandler(exceptions.BadRequest)
def handle_405(err):
    return render_template('errors/405.html'), 405


@views.errorhandler(exceptions.InternalServerError)
def handle_500(err):
    return render_template('errors/500.html'), 500

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='/index.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
    <nav>
        <a href="/">Home</a>
    </nav>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        &copy; Peter and Talha
    </footer>
</body>
</html>

App/templates/home.html
{% extends "base.html" %}
{% block content %}
<h1>{% block title %} Hello there, and welcome to Talha Briscoe's url shortener {% endblock %}</h1>
<form method = 'POST' action = "{{ url_for('views.new_link') }}">
    <input type = "text" name = "url" id="url_input">
    <input type="submit" id="url_submit">
</form>
{% endblock %}

App/templates/new_link.html
{% extends "base.html" %}
{% block content %}
<div id = 'links'>
    <h2>Here, have your little links</h2>
    





<div id ='align'>
<!-- Old Url: {{ url }} <br/> -->
<div id='new-link'>
<!-- New Url: <a id = "myInput" href="{{ url_for('views.new_link', shortened_url=new_link, _external=True) }}">{{ url_for('views.new_link', shortened_url=new_link, _external=True) }}</a> -->

<p>
    {{url}} can be found at
    <a href="http://localhost:5000/{{shortened_url}}"
      >http://localhost:5000/{{shortened_url}}</a
    >
  </p>

<img src="https://static1.cbrimages.com/wordpress/wp-content/uploads/2019/11/thanos-sunset.jpg" alt="Rhys">
</div>
</div>
{% endblock %}